name: "Test Github configuration sanity"
description: "Scan Github misconfigurations"
inputs:
    no-pull-request-target:
        description: "Enable scanning for pull_request_target usage in workflows"
        required: false
        default: "false"
    project-path:
        description: "Path to the project directory to scan"
        required: false
        default: "."
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v5
        - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
          shell: bash
        - name: "Scan for pull_request_target in workflows"
          if: inputs.no-pull-request-target == 'true'
          shell: bash
          run: scan.sh --path ${{ inputs.project-path }} --no-pull-request-target
